question_data = [
    {
        "category": "Science: Mathematics",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The &#039;Squaring the Circle&#039; problem is solvable.",
        "correct_answer": "False",
        "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "No Game No Life first aired in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "Adolf Hitler was tried at the Nuremberg trials.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "Thomas Crapper was a plumber who invented the flushing toilet.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "easy",
     "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "An equilateral triangle always has every angle measuring 60&deg;.", "correct_answer": "True",
     "incorrect_answers": ["False"]}
]
